(() => {
  'use strict';
  const G=n=>`atlas_greenwake_${String(n).padStart(2,'0')}`, M=n=>`atlas_moonfall_${String(n).padStart(2,'0')}`;
  const people={
    courier:{zone:'moonfall',x:1190,y:690,name:'Iona · Lantern Courier',actor:true},
    keeper:{zone:G(0),x:1050,y:600,name:'Keeper Anwen',actor:true},
    tracks:{zone:G(1),x:610,y:720,name:'Overturned Lantern Cart'},
    rootSeal:{zone:G(6),x:650,y:740,name:'Rootbound Beacon Seal'},
    ferryman:{zone:G(12),x:1050,y:600,name:'Tomas · Ferryman',actor:true},
    northRune:{zone:G(13),x:600,y:750,name:'Rain Inscription'},
    southRune:{zone:G(19),x:1190,y:750,name:'Hearth Inscription'},
    beacon:{zone:G(20),x:640,y:750,name:'The Broken Beacon'},
    envoy:{zone:G(23),x:1110,y:650,name:'Mira · Road Envoy',actor:true},
    archivist:{zone:M(0),x:1050,y:600,name:'Sera · Ash Archivist',actor:true},
    wreck:{zone:M(1),x:620,y:730,name:'Burned Survey Camp'},
    testimony:{zone:M(6),x:610,y:750,name:'The Last Keeper’s Record'},
    mourner:{zone:M(12),x:1050,y:600,name:'Oren · Bell Mourner',actor:true},
    bell:{zone:M(13),x:640,y:750,name:'The Bell of Names'},
    memorial:{zone:M(12),x:1250,y:730,name:'Lantern Memorial'},
    herbalist:{zone:G(0),x:1260,y:540,name:'Pip · Field Medic',actor:true},
    herbs:{zone:G(2),x:610,y:750,name:'Silverleaf Spring'},
    scout:{zone:G(7),x:620,y:750,name:'Edda · Stranded Scout',actor:true},
    letters:{zone:G(8),x:1130,y:740,name:'Lost Courier Satchel'},
    smith:{zone:G(12),x:1290,y:540,name:'Jory · Roadsmith',actor:true},
    tools:{zone:G(14),x:600,y:760,name:'Flooded Tool Chest'},
    astronomer:{zone:M(0),x:1260,y:540,name:'Leth · Stargazer',actor:true},
    star:{zone:M(4),x:650,y:740,name:'The Listening Stone'},
    quartermaster:{zone:M(12),x:1300,y:540,name:'Nim · Quartermaster',actor:true},
    ledger:{zone:M(7),x:610,y:750,name:'The Caravan’s True Ledger'},
  };
  const step=(chapter,title,at,text,kind='interact',extra={})=>({chapter,title,at,text,kind,...extra});
  const main=[
    step(2,'A Light Beyond Moonfall','courier','Speak to Iona beside the Moonfall Waystone.','interact',{line:'The Lens is awake—but the western beacon has gone dark. Anwen is sheltering travelers at the first Marches settlement. Take the eastern road from Moonfall; I will mark every turn.',gold:25,xp:35}),
    step(2,'The Broken Beacon','keeper','Find Keeper Anwen in the first Greenwake Marches settlement.','interact',{line:'The beacon did not simply fail. Someone cut its roots. Find the overturned lantern cart on the eastern road. Bring me the truth, not a convenient enemy.',xp:40}),
    step(2,'Tracks in the Rain','tracks','Inspect the overturned cart east of Anwen’s settlement.','interact',{line:'No bodies. No stolen coins. Just roots wound around a lantern bearing a keeper’s seal. Three corrupted echoes still circle the wreck.',xp:35}),
    step(2,'The Cart’s Last Watch','tracks','Defeat 4 threats around the lantern cart.','kill',{count:4,xp:75,gold:45}),
    step(2,'The Rootbound Guardian','rootSeal','Defeat the Rootbound Guardian in the western dungeon. Recommended level 6.','boss',{boss:'Rootbound Guardian',level:6,hp:1180,xp:110}),
    step(2,'A Keeper’s Warning','rootSeal','Read the freed beacon seal.','interact',{line:'“We sealed the roads to keep the hunger out. We forgot that people live between the seals.” Two inscriptions can wake the beacon. Tomas at the river settlement knows their names.',xp:45}),
    step(2,'The Ferryman’s Price','ferryman','Speak to Tomas at the southern river settlement.','choice',{line:'Tomas has one wagon of supplies. Send it to displaced families, or equip the beacon repair crew? Both routes restore the beacon; the people will remember how.',choices:[['shelter','Supply the families · 2 healing tonics'],['repair','Equip the repair crew · 4 warden alloy']],xp:65,gold:50}),
    step(2,'What the Rain Remembers','northRune','Read the Rain Inscription east of the river settlement.','interact',{line:'The first verse is an apology: “May no traveler be left outside our light.” The Lens holds its melody.',xp:50}),
    step(2,'What the Hearth Keeps','southRune','Read the Hearth Inscription on the southern road.','interact',{line:'The second verse answers: “A road belongs to those who walk it.” Together the verses reveal a name buried beneath the beacon.',xp:50}),
    step(2,'The Beacon Devourer','beacon','Defeat the Beacon Devourer. Recommended level 7.','boss',{boss:'Beacon Devourer',level:7,hp:1280,xp:140}),
    step(2,'Light for the Living','beacon','Relight the beacon with the two remembered verses.','interact',{line:'Warm light runs along every road. The roots loosen. In the distance, lanterns answer one by one. The Lens reveals another wound: a bell in Moonfall Basin, ringing for people whose names have been erased.',xp:140,gold:180,item:'sentinel_shield',flag:'beaconLit'}),
    step(2,'The Road Opens','envoy','Meet Mira at the eastern Marches crossing.','interact',{line:'You gave them a road, not another ruler. I am coming with you. Sera keeps the Basin archive beyond this crossing. Show her the name the beacon remembered: Oren.',xp:80,flag:'miraRoads'}),
    step(3,'Ashes Under the Road','archivist','Speak to Sera in the first Moonfall Basin settlement.','interact',{line:'Oren was not a traitor. He tried to stop the keepers from feeding memories to the Ways. Search the burned survey camp east of here. Someone is destroying what remains of his work.',xp:60}),
    step(3,'The Surveyors’ Silence','wreck','Examine the burned survey camp.','interact',{line:'A child’s drawing survives beneath the ash: a bell, a house, seven names. The constructs guarding this camp are destroying evidence, not defending it.',xp:45}),
    step(3,'Break the Censors','wreck','Defeat 5 threats near the burned camp.','kill',{count:5,xp:100,gold:70}),
    step(3,'The Unwritten Oath','testimony','Recover the keeper’s testimony in the western archive ruins.','interact',{line:'Oren’s record names the cost of the old roads: every opening consumed a memory. His final experiment stored them in a bell instead. It can still be opened—but its sentinel mistakes every visitor for a thief.',xp:75}),
    step(3,'The Man Without a Name','mourner','Find Oren in the southern Basin settlement.','interact',{line:'I remember that I loved someone. I do not remember her face. If the bell still holds our names, please bring them home. Do not turn them into another weapon.',xp:60}),
    step(3,'Sentinel of Lost Names','bell','Defeat the Bell Sentinel east of Oren’s settlement. Recommended level 8.','boss',{boss:'Bell Sentinel',level:8,hp:1380,xp:160}),
    step(3,'Who Owns a Memory?','bell','Choose the fate of the names inside the bell.','choice',{line:'The names can return directly to the families, or be preserved with copies in a public archive. Neither choice feeds the old machine. What should the new roads remember?',choices:[['families','Return the names · restoration supplies'],['archive','Build the public record · faction reputation']],xp:100,flag:'namesFreed'}),
    step(3,'A Name Spoken Aloud','memorial','Light the memorial in Oren’s settlement.','interact',{line:'Oren speaks his wife’s name, then laughs because he remembers her laugh. Around the memorial, strangers begin greeting one another. The roads are quiet—not empty, but finally at peace.',xp:200,gold:260,item:'warden_helm',flag:'basinRestored'}),
    step(3,'The Roads We Choose','archivist','Return to Sera to close the Basin investigation.','interact',{line:'Two regions can breathe again. There are still people here who need a Roadbearer: read your journal’s side stories, finish the old contracts, or explore beyond the eastern crossing. This concludes the currently authored main chapters; the wider world remains open.',xp:100,gold:100}),
  ];
  const sides=[
    {id:'silverleaf',name:'A Remedy for the Road',giver:'herbalist',at:'herbs',kind:'interact',text:'Gather silverleaf at the spring two roads east of Pip.',pitch:'Pip’s patients cannot afford another night of fever. Silverleaf grows beside a spring on the eastern roads. Bring a cutting, not the whole plant.',found:'You take a careful cutting, leaving the silverleaf to grow again.',end:'Pip divides the leaves between six cups. “Enough for everyone. That matters.”',gold:90,xp:70,item:'aether_draught'},
    {id:'missingScout',name:'Someone Left Behind',giver:'keeper',at:'scout',kind:'interact',text:'Find Edda on the road southeast of the first settlement.',pitch:'Anwen refuses to mark Edda dead. Find the scout on the southeast road and give her the safe route home.',found:'Edda has been keeping a stranger alive. You mark a safe route; both can walk home without crossing the old ambush.',end:'Edda and her patient reached the lanterns. Anwen puts two extra bowls on the table.',gold:110,xp:85,item:'trail_helm'},
    {id:'letters',name:'Letters Never Sent',giver:'courier',at:'letters',kind:'interact',text:'Recover Iona’s satchel in the eastern Greenwake Marches.',pitch:'Iona’s lost satchel carries letters, not valuables. Some are the last words their families will ever receive.',found:'The letters are damp but legible. One begins: “If I do not return, please plant the orchard anyway.”',end:'Iona ties the satchel shut. “I can finish my route now.”',gold:95,xp:80},
    {id:'riverWatch',name:'The Last Ferry',giver:'ferryman',at:'tools',kind:'kill',count:5,text:'Defeat 5 road threats two crossings east of Tomas.',pitch:'The ferry is ready, but its passengers cannot reach the river. Clear the eastern approach so the next crossing carries people instead of supplies.',end:'The first ferry leaves full. Tomas gives you the fare the passengers insisted on paying.',gold:150,xp:110,item:'scout_belt'},
    {id:'tools',name:'A Smith Without a Forge',giver:'smith',at:'tools',kind:'interact',text:'Recover Jory’s tools from the flooded chest on the eastern road.',pitch:'Jory can rebuild travelers’ wagons, but the flood took his tools. Recover the chest before rust finishes the job.',found:'The oilcloth held. Under the tools is a small toy hammer, carefully wrapped.',end:'Jory sets the toy aside for his daughter. His roadside repairs reopen; all your shop prices fall by 5%.',gold:100,xp:90,flag:'roadDiscount'},
    {id:'star',name:'The Star That Listens',giver:'astronomer',at:'star',kind:'interact',text:'Listen at the standing stone on the eastern Basin road.',pitch:'Leth hears a voice whenever the standing stone catches starlight. It asks a question no chart can answer: “Are you still there?”',found:'You answer. For a moment the stone is warm. A distant voice says “Thank you,” and the light becomes still.',end:'Leth closes the chart. Some discoveries are not coordinates.',gold:110,xp:100,item:'lantern_charm'},
    {id:'ledger',name:'The Price of Safe Passage',giver:'quartermaster',at:'ledger',kind:'interact',text:'Find the caravan ledger northeast of the Basin archive ruins.',pitch:'Nim suspects the caravan losses are being charged twice. Find the original ledger. A road should not cost more than the people walking it.',found:'The ledger lists imaginary escorts and real widows. You preserve the evidence.',end:'Nim refunds the families before confronting the broker. Your faction hears who brought the proof.',gold:160,xp:110,rep:20},
    {id:'nightWatch',name:'Lanterns Against the Dark',giver:'mourner',at:'star',kind:'kill',count:6,text:'Defeat 6 threats near the eastern Basin standing stone.',pitch:'Oren still lights a lantern for travelers after dusk. Help him make the eastern road safe enough that they can reach it.',end:'Oren hangs six new lanterns along the road. “Not a wall,” he says. “A welcome.”',gold:170,xp:130,item:'rune_helm'},
  ];
  function init(S){const old=S.story||{};S.story={version:1,step:Math.max(0,Math.min(main.length,Math.floor(Number(old.step)||0))),kills:Math.max(0,Number(old.kills)||0),flags:{...(old.flags||{})},choices:{...(old.choices||{})},side:{...(old.side||{})},tracked:old.tracked||'main'};return S.story;}
  const unlocked=S=>S.mainStep>=8;
  function current(S){return unlocked(S)?main[S.story?.step||0]:null;}
  function sideState(S,q){return S.story?.side[q.id]||{status:'available',progress:0};}
  function target(S){if(!unlocked(S))return null;const q=sides.find(q=>q.id===S.story?.tracked);if(q){const s=sideState(S,q);if(s.status!=='complete')return {...people[s.status==='active'?q.at:q.giver],id:s.status==='active'?q.at:q.giver,title:q.name,kind:s.status==='active'?q.kind:'interact'};}const m=current(S);return m?{...people[m.at],id:m.at,title:m.title,kind:m.kind}:null;}
  function objective(S){const t=target(S),m=current(S),q=sides.find(q=>q.id===S.story?.tracked);if(q&&sideState(S,q).status!=='complete'){const s=sideState(S,q);return[q.name,s.status==='available'?`Speak to ${people[q.giver].name}`:s.status==='ready'?`Return to ${people[q.giver].name}`:q.text+(q.kind==='kill'?` · ${s.progress}/${q.count}`:'')];}return m?[m.title,m.text+(m.kind==='kill'?` · ${S.story.kills}/${m.count}`:'')]:['The Roads Restored','Main chapters complete · Choose a side story in your journal'];}
  function objects(S){if(!unlocked(S))return [];const needed=new Set(sides.flatMap(q=>[q.giver,...(sideState(S,q).status==='active'?[q.at]:[])]));if(S.story.flags.beaconLit)needed.add('beacon');if(S.story.flags.basinRestored)needed.add('memorial');const m=current(S);if(m)needed.add(m.at);return [...needed].filter(id=>people[id].zone===S.zone).map(id=>({id:`story:${id}`,storyId:id,kind:'story',...people[id],label:people[id].actor?'Talk':'Inspect'}));}
  function finish(S,m,h,choice){const index=S.story.step;if(choice)S.story.choices[index]=choice;if(m.flag)S.story.flags[m.flag]=true;S.story.step++;S.story.kills=0;h.reward(m);if(choice==='shelter'||choice==='families'){h.item('tonic');h.item('tonic');}if(choice==='repair')S.materials.wardenAlloy+=4;if(choice==='archive'&&S.faction)S.factionRep[S.faction]+=30;h.changed();}
  function action(S,id,action,h){init(S);if(!unlocked(S)||!people[id]||S.zone!==people[id].zone)return false;const m=current(S);
    if(action.startsWith('main:')){if(!m||m.at!==id||!['interact','choice'].includes(m.kind))return false;const choice=action.slice(5);if(m.kind==='choice'&&!m.choices.some(c=>c[0]===choice))return false;finish(S,m,h,m.kind==='choice'?choice:null);return true;}
    const [verb,qid]=action.split(':'),q=sides.find(q=>q.id===qid);if(!q)return false;const s=sideState(S,q);
    if(verb==='accept'&&id===q.giver&&s.status==='available'){S.story.side[qid]={status:'active',progress:0};S.story.tracked=qid;h.changed();return true;}
    if(verb==='find'&&id===q.at&&q.kind==='interact'&&s.status==='active'){s.status='ready';s.progress=1;h.changed();return true;}
    if(verb==='claim'&&id===q.giver&&s.status==='ready'){s.status='complete';if(q.flag)S.story.flags[q.flag]=true;h.reward(q);if(q.rep&&S.faction)S.factionRep[S.faction]+=q.rep;if(S.story.tracked===qid)S.story.tracked='main';h.changed();return true;}return false;
  }
  function kill(S,e,h){if(!unlocked(S))return;init(S);const m=current(S);if(m&&people[m.at].zone===S.zone){if(m.kind==='kill'){S.story.kills++;if(S.story.kills>=m.count)finish(S,m,h);}else if(m.kind==='boss'&&e.storyBoss===S.story.step)finish(S,m,h);}
    for(const q of sides){const s=sideState(S,q);if(s.status==='active'&&q.kind==='kill'&&people[q.at].zone===S.zone){s.progress=Math.min(q.count,s.progress+1);if(s.progress>=q.count){s.status='ready';h.changed();}}}}
  function panel(S,id){const p=people[id],m=current(S);let html='';if(m?.at===id){html+=`<article class="story-card"><span class="choice-tag">Main story · Chapter ${m.chapter} · ${m.title}</span><p>${m.line||m.text}</p>`;if(m.kind==='choice')html+=m.choices.map(c=>`<button data-story-action="main:${c[0]}" data-story-person="${id}">${c[1]}</button>`).join('');else if(m.kind==='interact')html+=`<button data-story-action="main:continue" data-story-person="${id}">Continue the story</button>`;else html+=`<p>${m.kind==='kill'?`${S.story.kills}/${m.count} threats defeated`:'The guardian must fall before the seal will answer.'}</p>`;html+='</article>';}
    for(const q of sides){const s=sideState(S,q);if(q.giver===id){html+=`<article class="story-card"><span class="choice-tag">Side story · ${s.status}</span><h3>${q.name}</h3><p>${s.status==='complete'?q.end:s.status==='ready'?q.end:q.pitch}</p><p>${q.gold} gold · ${q.xp} XP${q.item?' · equipment or supplies':''}</p>`;if(['available','ready'].includes(s.status))html+=`<button data-story-action="${s.status==='ready'?'claim':'accept'}:${q.id}" data-story-person="${id}">${s.status==='ready'?'Claim reward':'Accept side quest'}</button>`;else if(s.status==='active')html+=`<p>${q.text}</p><button data-story-track="${q.id}">Track this quest</button>`;html+='</article>';}
      if(q.at===id&&s.status==='active'&&q.kind==='interact')html+=`<article class="story-card"><h3>${q.name}</h3><p>${q.found}</p><button data-story-action="find:${q.id}" data-story-person="${id}">Recover and return</button></article>`;}
    return {title:p.name,html:html||'<p>The road is quiet here. Your journal records the next destination.</p>'};}
  function journal(S,atlas){if(!unlocked(S))return '';const m=current(S),tracked=S.story.tracked,place=id=>atlas.get(people[id].zone)?.name||'Moonfall Ruins';return `<div class="story-intro"><span class="choice-tag">The continuing story</span><h3>${m?`Chapter ${m.chapter} · ${m.title}`:'Chapters II & III complete'}</h3><p>${m?m.text:'The beacon burns and the names are restored. These are the currently authored main chapters; the wider world and unfinished side stories remain open.'}</p><p>${S.story.step}/${main.length} story objectives complete${m?` · ${place(m.at)}`:''}</p><button data-story-track="main">${tracked==='main'?'Tracking main story':'Track main story'}</button></div><h3>Side stories · ${sides.filter(q=>sideState(S,q).status==='complete').length}/${sides.length}</h3>${sides.map(q=>{const s=sideState(S,q);return `<article class="journal-card story-card"><span class="choice-tag">${s.status} · ${place(q.giver)}</span><h3>${q.name}</h3><p>${s.status==='complete'?q.end:s.status==='available'?`Speak to ${people[q.giver].name}. ${q.pitch}`:s.status==='ready'?`Return to ${people[q.giver].name} for your reward.`:q.text}</p><p>${q.gold}g · ${q.xp} XP${q.kind==='kill'&&s.status==='active'?` · ${s.progress}/${q.count}`:''}</p>${s.status!=='complete'?`<button data-story-track="${q.id}">${tracked===q.id?'Currently tracked':'Show me the way'}</button>`:''}</article>`;}).join('')}<details class="journal-card"><summary>Completed main-story chapters and choices</summary>${main.slice(0,S.story.step).map((m,i)=>`<p>✓ ${m.title}${S.story.choices[i]?` · ${m.choices.find(c=>c[0]===S.story.choices[i])?.[1]||''}`:''}</p>`).join('')}</details>`;}
  function drawProp(c,o,S){const id=o.storyId;c.save();c.translate(o.x,o.y);c.fillStyle='#02120d66';c.beginPath();c.ellipse(0,12,46,15,0,0,7);c.fill();
    if(id==='beacon'||id==='rootSeal'||id==='star'||id==='memorial'){
      const lit=id==='beacon'?S.story.flags.beaconLit:id==='memorial'?S.story.flags.basinRestored:false;
      for(let r=3;r>0;r--){c.fillStyle=r%2?'#677f73':'#364d45';c.beginPath();c.ellipse(0,12-r*4,r*19,r*8,0,0,7);c.fill();}
      if(id==='memorial'){for(let i=0;i<7;i++){const a=i/7*Math.PI*2,x=Math.cos(a)*42,y=Math.sin(a)*18;c.fillStyle='#85643b';c.fillRect(x-3,y-18,6,25);c.fillStyle=lit?'#ffe29a':'#748179';c.fillRect(x-6,y-28,12,13);}}
      else{c.fillStyle='#253e39';c.fillRect(-18,-77,36,82);c.strokeStyle='#b69e67';c.lineWidth=3;c.strokeRect(-18,-77,36,82);c.fillStyle=lit?'#ffdb78':id==='star'?'#b3b6ff':'#72dccc';c.shadowColor=c.fillStyle;c.shadowBlur=lit?28:8;c.beginPath();c.moveTo(0,-100);c.lineTo(19,-65);c.lineTo(0,-40);c.lineTo(-19,-65);c.closePath();c.fill();c.shadowBlur=0;}
    }else if(id==='bell'){c.fillStyle='#79613a';c.fillRect(-34,-94,8,102);c.fillRect(26,-94,8,102);c.fillRect(-38,-98,76,9);c.fillStyle=S.story.flags.namesFreed?'#ead28c':'#b28e4d';c.beginPath();c.moveTo(-12,-72);c.quadraticCurveTo(-27,-45,-28,-24);c.lineTo(28,-24);c.quadraticCurveTo(27,-45,12,-72);c.closePath();c.fill();c.fillRect(-33,-26,66,7);c.fillStyle='#5a4528';c.fillRect(-3,-21,6,13);
    }else if(id==='tracks'||id==='wreck'){c.fillStyle='#493a2c';c.fillRect(-41,-32,82,36);c.fillStyle='#97734b';for(let y=-31;y<0;y+=9)c.fillRect(-43,y,86,5);c.strokeStyle='#b29460';c.lineWidth=4;for(const x of[-32,32]){c.beginPath();c.arc(x,9,14,0,7);c.stroke();c.beginPath();c.moveTo(x-13,9);c.lineTo(x+13,9);c.stroke();}c.fillStyle=id==='wreck'?'#292623':'#bdad7a';c.fillRect(-20,-52,43,24);c.fillStyle='#e7c778';c.fillRect(32,-51,9,15);
    }else if(id==='herbs'){for(let i=0;i<7;i++){const x=i*10-30,y=(i%3)*8;c.fillStyle='#435f3a';c.fillRect(x,y-27,4,33);c.fillStyle='#9ce1a3';c.beginPath();c.ellipse(x-5,y-19,9,4,-.5,0,7);c.ellipse(x+7,y-11,9,4,.5,0,7);c.fill();c.fillStyle='#eef5c4';c.fillRect(x-1,y-33,7,7);}
    }else if(id==='northRune'||id==='southRune'||id==='testimony'){c.fillStyle='#536866';c.fillRect(-25,-66,50,76);c.fillStyle='#8daba0';c.fillRect(-20,-61,40,6);c.strokeStyle='#9de0ce';c.lineWidth=2;for(let i=0;i<3;i++){c.beginPath();c.moveTo(-12,-43+i*14);c.lineTo(4,-49+i*14);c.lineTo(13,-37+i*14);c.stroke();}
    }else{c.fillStyle='#604b35';c.fillRect(-27,-26,54,36);c.fillStyle='#b89964';c.fillRect(-29,-30,58,9);c.fillStyle='#ddd0a4';c.fillRect(-17,-39,34,24);c.strokeStyle='#62594b';for(let i=0;i<3;i++){c.beginPath();c.moveTo(-11,-34+i*6);c.lineTo(11,-34+i*6);c.stroke();}}
    c.restore();
  }
  window.EVERLIGHT_STORY={version:28,main,sides,people,init,current,target,objective,objects,action,kill,panel,journal,unlocked,drawProp};
})();
